# Generated by Django 6.0 on 2026-01-21 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(blank=True, choices=[('signup', 'Signup'), ('change_email', 'Change Email')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='spending_insights',
            field=models.BooleanField(default=False),
        ),
    ]
