# Generated by Django 6.0 on 2026-01-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='icon',
        ),
    ]
