# Generated by Django 6.0 on 2026-01-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_goalcontribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_contribution',
        ),
    ]
