# Generated by Django 6.0 on 2026-01-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notificationevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationevent',
            old_name='notification_type',
            new_name='type',
        ),
    ]
