# Generated by Django 6.0 on 2026-01-05 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_goal_current_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
