# Generated by Django 6.0 on 2026-01-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_notification_type_notificationevent_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationevent',
            old_name='type',
            new_name='notification_type',
        ),
    ]
