# Generated by Django 6.0 on 2026-01-24 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_budget_month_alter_budget_year'),
        ('myapp', '0004_rename_type_notificationevent_notification_type'),
    ]

    operations = [
    ]
