# Generated by Django 6.0 on 2026-01-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_transaction'),
        ('myapp', '0004_goal_created'),
    ]

    operations = [
    ]
